### ISSUE TITLE
The game introduces new login data. . . This FGO-Daily-Login is currently completely out of service 

### ISSUE THREAD

**Issue by DNNDHH** [O-Isaac/FGO-Daily-Login#14]
<html>
<body>
-- | --

idempotencyKeySignature  

Added idempotencyKeySignature ，If you don’t add it, it will

ERROR [ErrorCode: 99]
サーバ内部で問題が発生したため、処理が続行できません。

</body>
</html>

**Comment by DNNDHH** [comment]
They may ban accounts that do not have this value in the request data, and you should stop using them until the problem is solved.

**Comment by ye0429** [comment]
我是安卓开放， 但是对于 逆向不是很了解= =   兄弟   然后FGO这边还是有一点疑问 还有你之前说的新加密问题，    能留个联系方式么。。。 就是游戏交流  我没有恶意  因为都是自己一个人玩游戏  想找个伴。。。

**Comment by ye0429** [comment]
希望能得到回复。。。 没有恶意 就是单纯想找个人一起玩    我也爱玩ps4游戏  拜托了兄弟= =

**Comment by minhdaohuu** [comment]
Does anyone have a solution for this? ^^

**Comment by Akane7101** [comment]
Fixed now i think
Dunno what happened but i guess they reverted back to the old login data..
Well.. As long as it works

**Comment by DNNDHH** [comment]
> Fixed now i think
> Dunno what happened but i guess they reverted back to the old login data..
> Well.. As long as it works 

they may think this reduces the number of active users (bot), so they restore the previous login... or they may perform a more complete verification check normally

**Comment by O-Isaac** [comment]
I Will check that

**Comment by O-Isaac** [comment]
I Will stop this project, spend much time
