### ISSUE TITLE
Dont know how to use

### ISSUE THREAD

**Issue by Friendclubattle78** [O-Isaac/FGO-Daily-Login#3]
**Would you mind record an video for FGO daily login? 
Im still dont understand how to do it.**

**Comment by O-Isaac** [comment]
I'm sorry but for now I can't make the video.

**Comment by Friendclubattle78** [comment]
> I'm sorry but for now I can't make the video.

****When you can make it?**
(When you make the video please DM me by discord:** ) 
🖤𝕯𝖊𝖆𝖙𝖍 ( 𝕿𝖍𝖊 𝕿𝖗𝖚𝖊 𝕯𝖊𝖆𝖙𝖍 )🖤#0813   or  ~Tokarin~#2613
