### ISSUE TITLE
When you can make a tutorial video?

### ISSUE THREAD

**Issue by Friendclubattle78** [O-Isaac/FGO-Daily-Login#4]
**When you have time to make the video please give link here for people to know.**
**Hope you can make it for soon @O-Isaac.** 
**Discord:** 🖤𝕯𝖊𝖆𝖙𝖍 ( 𝕿𝖍𝖊 𝕿𝖗𝖚𝖊 𝕯𝖊𝖆𝖙𝖍 )🖤#0813

**Comment by Friendclubattle78** [comment]
I also sent friend request you on **Discord**.

**Comment by O-Isaac** [comment]
Check pinned issue #13
