### ISSUE TITLE
Blue Apple

### ISSUE THREAD

**Issue by O-Isaac** [O-Isaac/FGO-Daily-Login#8]
Add option to make blue apple, should use theses options in secrets:
- MAKE_BLUE_APPLE: Cron Pattern

**Comment by paressuex11** [comment]
I've added this `MAKE_BLUE_APPLE: 15 19 * * *`to my secrets.But it appears nothing happened.

**Comment by O-Isaac** [comment]
The functionality is not yet implemented. I am working on it, but I am having trouble implementing that functionality.

**Comment by paressuex11** [comment]
Would you mind sharing how you find these http apis? Ive tried to do packet sniff with fiddler,but nothing was catched except some asset files.

**Comment by paressuex11** [comment]
I used a frida script to bypass ssl pinning, but it didnt work though.

**Comment by O-Isaac** [comment]
You need make c hook function

**Comment by O-Isaac** [comment]
Ill add this function in next version, i want close #13
